"""cria tabela campaigns

Revision ID: 4778b0f580c9
Revises: 62e4990495fc
Create Date: 2026-08-12 17:26:18.304477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, usados pelo Alembic.
revision: str = '4778b0f580c9'
down_revision: Union[str, None] = '62e4990495fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('goal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'funded', 'completed', 'cancelled', name='campaign_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_animal_id'), 'campaigns', ['animal_id'], unique=False)
    op.create_index(op.f('ix_campaigns_created_by'), 'campaigns', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_created_by'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_animal_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
