"""cria tabela animals

Revision ID: 62e4990495fc
Revises: 173de88fe9c5
Create Date: 2026-08-12 16:44:11.856891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, usados pelo Alembic.
revision: str = '62e4990495fc'
down_revision: Union[str, None] = '173de88fe9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registered_by', sa.UUID(), nullable=False),
    sa.Column('species', sa.Enum('dog', 'cat', name='animal_species'), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'unknown', name='animal_sex'), server_default='unknown', nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_sterilized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('stray', 'adopted', 'in_shelter', 'deceased', name='animal_status'), server_default='stray', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_registered_by'), 'animals', ['registered_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_registered_by'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
