"""adiciona reporter_id em sightings

Revision ID: ab27e743018d
Revises: febcf0d5a6bf
Create Date: 2026-08-11 20:19:29.583773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, usados pelo Alembic.
revision: str = 'ab27e743018d'
down_revision: Union[str, None] = 'febcf0d5a6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sightings', sa.Column('reporter_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_sightings_reporter_id'), 'sightings', ['reporter_id'], unique=False)
    op.create_foreign_key('fk_sightings_reporter_id_users', 'sightings', 'users', ['reporter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sightings_reporter_id_users', 'sightings', type_='foreignkey')
    op.drop_index(op.f('ix_sightings_reporter_id'), table_name='sightings')
    op.drop_column('sightings', 'reporter_id')
    # ### end Alembic commands ###
