"""cria tabela donations

Revision ID: d8f5ca62a9c3
Revises: 4778b0f580c9
Create Date: 2026-08-12 19:46:06.489969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, usados pelo Alembic.
revision: str = 'd8f5ca62a9c3'
down_revision: Union[str, None] = '4778b0f580c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'refunded', name='donation_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index(op.f('ix_donations_campaign_id'), 'donations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_campaign_id'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
