"""adiciona indice em created_at para listagens

Revision ID: e7cabae69e24
Revises: d8f5ca62a9c3
Create Date: 2026-08-13 19:17:19.121708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, usados pelo Alembic.
revision: str = 'e7cabae69e24'
down_revision: Union[str, None] = 'd8f5ca62a9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_animals_created_at'), 'animals', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_donations_created_at'), 'donations', ['created_at'], unique=False)
    op.create_index(op.f('ix_sightings_created_at'), 'sightings', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sightings_created_at'), table_name='sightings')
    op.drop_index(op.f('ix_donations_created_at'), table_name='donations')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_index(op.f('ix_animals_created_at'), table_name='animals')
    # ### end Alembic commands ###
